server:
  port: 8080
  servlet:
    context-path: /app
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/space"
    password: manhden123
    username: root
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
      enabled: true




  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#
##      hibernate:
#        format_sql: true

logging:
  level:
    web: debug
    sql: debug

    logging:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE





jwt:
  signerKey: "ZdvNMDHyNDEhxmiBpJy4ZLTnvdeaXursPU5Es/3LyPfn6uVUHC2xq0E+JASVForD"




